# This is the project file for the automated build system travis (travis-ci.com).
sudo: required

dist: trusty

language: c

compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhidapi-dev
  - ./autogen.sh

install: true # skip install step

script: ./configure && make
